### ISSUE TITLE
The BytecodeReadingParanamer throws an Exception in Java8 when the class contains lambda expressions 

### ISSUE THREAD

**Issue by stephane-bastian** [paul-hammant/paranamer#17]
Hello,
I just came across this issue where the BytecodeReadingParanamer throws an ArrayIndexOutOfBoundsException in Java8 when the class contains lambda expressions.

Here is an excerpt of the stack trace:

java.lang.ArrayIndexOutOfBoundsException: 28263
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.accept(BytecodeReadingParanamer.java:563)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.access$200(BytecodeReadingParanamer.java:338)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:103)

**Comment by nartamonov** [comment]
This bug also affects JBehave, see http://jira.codehaus.org/browse/JBEHAVE-1069

**Comment by electrum** [comment]
Any plans to fix this?

**Comment by garcia-jj** [comment]
If you are running your code under Java 8, you don't need paranamer. You need just to compile your code with `-parameters`. In your code you can use: `Method.getParameters()`.

**Comment by electrum** [comment]
There are libraries using paranamer that run on older JDKs but read classes from Java 8. Also, the fact that Java 8 made the flag a non-default option means you still need a fallback :(

**Comment by garcia-jj** [comment]
Hmm, now I see. I fixed the code today, but I need to write more tests to check if the change works with codes compiled with JDK prior Java 8. Soon I will send a pull request.

**Comment by muminc** [comment]
This bug also affects Orika-mapper, see https://github.com/orika-mapper/orika/issues/60

**Comment by garcia-jj** [comment]
I fixed the code at pull request #20, waiting for @paul-hammant  review.

**Comment by paul-hammant** [comment]
The PR is in. There's a failure with QDoxParanamerTestCase though. I need to work though that. I deeply suspect I messed up the merging of Robert Scholte's QDox 2 change. Aside from that I need to change the POM to no longer refer to Codehaus - though I have to copy - https://github.com/SeleniumHQ/fluent-selenium/blob/master/java/pom.xml I'll explain more if you hit me up in email.

**Comment by rfscholte** [comment]
IIRC the root cause of the failing test has to do with the change in QDox2 where a constructor is now a Constructor (like in java.lang.reflect) instead of a special kind of Method. The order of parsing methods+constructors has changed due to this. Hopefully this a good clue to get it fixed in Paranamer.
