### ISSUE TITLE
Please consider to tag new releases  (Github has 2.3 but latest version is 2.15)

### ISSUE THREAD

**Issue by apoleon** [paul-hammant/paranamer#18]
Hello,

please consider to tag new releases for Github, so that it is possible to download releases as tarballs. It appears that the latest version of Paranamer is 2.15 (according to Maven) but Github only has 2.3 from 2010). Thank you.

**Comment by ebourg** [comment]
Here are the commands to add the missing tags:

    git tag d77b23a paranamer-2.7
    git tag fb0518b paranamer-2.6.1
    git tag 4b7e215 paranamer-2.6
    git tag 0457e01 paranamer-2.5.8
    git tag fc84c32 paranamer-2.5.7
    git tag 7edc202 paranamer-2.5.6
    git tag 97c0bb5 paranamer-2.5.5
    git tag 9cde58d paranamer-2.5.4
    git tag 952a832 paranamer-2.5.3
    git tag 113f5d1 paranamer-2.5.2
    git tag 680903f paranamer-2.5.1
    git tag 08593ce paranamer-2.5
    git tag ab5377e paranamer-2.4.1
    git tag d95db40 paranamer-2.4
    git push --tags

**Comment by paul-hammant** [comment]
Tags were there locally, just not pushed. Perhaps they were pushed to Codehaus, but not GH.

**Comment by ebourg** [comment]
Thank you
