### ISSUE TITLE
Please update documentation: BytecodeReadingParanamer does not work for Interfaces

### ISSUE THREAD

**Issue by rwitzel** [paul-hammant/paranamer#19]
Hi Paul,

according to your test BytecodeReadingParanamerTestCase.testLookupParameterNamesForInterfaceMethod() parameter names cannot by extracted from methods of interfaces.

Would you mind to add that information to both the README.md and the class comment? This could save some people a lot of time when they run into unexpected behaviour.

Regards
Rod

**Comment by teras** [comment]
Is this a limitation of the library, or just "the information is not there" ?

**Comment by paul-hammant** [comment]
It is impossible sadly. the compiler does not make that info for .class files that are interfaces

**Comment by paul-hammant** [comment]
documentation updated to state this clearly
