### ISSUE TITLE
Release latest changes to maven central

### ISSUE THREAD

**Issue by muminc** [paul-hammant/paranamer#22]
Thanks for recent fix #17 for lambda expressions. 

Please consider releasing update to maven central, projects such [jbehave] (https://jira.codehaus.org/browse/JBEHAVE-1069) and [orika-mapper](https://github.com/orika-mapper/orika/issues/60) are waiting for this.

**Comment by garcia-jj** [comment]
+1 to release last changes, The issue #17  fixed by me affect some opensource project I contribute, like vraptor4. Releasing will save some souls.

**Comment by janschaefer** [comment]
[JGiven](https://github.com/TNG/JGiven/issues/85) is also waiting :-)

**Comment by paul-hammant** [comment]
I'm having problems with the "ant" module when doing release:prepare. I'll keep looking - sorry guys.

**Comment by garcia-jj** [comment]
Any chances to get this new release before a new major version of vraptor4 planing to next week? Thank you.

**Comment by paul-hammant** [comment]
2.8 released - thanks go to @garcia-jj
