### ISSUE TITLE
Unable to download 2.5.6 using sbt

### ISSUE THREAD

**Issue by ulejon** [paul-hammant/paranamer#23]
Hi, 

I'm unable to resolve paranamer 2.6 when building my project with sbt. 
You can find more info about this issue at stackoverflow: http://stackoverflow.com/questions/30860963/unable-to-download-com-thoughtworks-paranamerparanamer2-5-6-with-sbt

Cheers

**Comment by paul-hammant** [comment]
I think this issue (with oss.sonatype.org) has gone away.
