### ISSUE TITLE
Lookup parameter names of interface's method with generics

### ISSUE THREAD

**Issue by pedrografael** [paul-hammant/paranamer#26]
Hi!

CachingParanamer.lookupParameterNames method returns an empty array when I try to get parameter names of interface's method with generics.
e.g.:
public interface If &lt;R&gt; {
	void methodIf(String parameterName1, R parameterName2);
}
Could you help me?
Thank you!

**Comment by paul-hammant** [comment]
Which version of Paranamer?

**Comment by pedrografael** [comment]
2.8

**Comment by garcia-jj** [comment]
Accoriding the issue #19 its not possible to get information from interfaces if you are using ´BytecodeReadingParanamer´.

**Comment by pedrografael** [comment]
Hi garcia-jj, thanks for your reply!
I am using CachingParanamer. Inside, it uses DefaultParanamer. I am generating paranamer data with maven plugin.
Interfaces without generics work. The problem is interfaces with generics, like my example.

**Comment by garcia-jj** [comment]
HI @pedrografael. When you are using generics, Java assumes your `<R>` type as java.lang.Object.

Can you test your code using something like this?

```java
	public static final String __PARANAMER_DATA = "v1.0 \n"
		+ "methodIf java.lang.String,java.lang.Object parameterName1,parameterName2 \n";
```

**Comment by pedrografael** [comment]
Hi garcia-jj!
Yeh, it works. Thank you very much!

**Comment by garcia-jj** [comment]
You're welcome. Can I close this issue?

**Comment by pedrografael** [comment]
Yes, please!
