### ISSUE TITLE
can i copy your code for tio

### ISSUE THREAD

**Issue by tywo45** [paul-hammant/paranamer#32]
hi, i am t-io'author, i have used your code through pom
`<dependency>
				<groupId>com.thoughtworks.paranamer</groupId>
				<artifactId>paranamer</artifactId>
				<version>2.8</version>
			</dependency>`

but t-io'user want to reduce t-io'dependence, so, can i copy your code into t-io'project?

t-io'project address: https://gitee.com/tywo45/t-io

**Comment by paul-hammant** [comment]
BSD is quite a permissive license - see LICENSE.txt in this repo. That's all you need to follow, tywo45 :)

If you do place paranamer code in your repo (within the terms of the BSD license), you SHOULD make the package names unique (`com.thoughtworks.paranamer` should become `com.tio.thoughtworksparanamer` or similar), and you should link back to this repo.

**Comment by tywo45** [comment]
i have done, 

please review: https://gitee.com/tywo45/t-io/tree/master/src/utils/src/main/java/org/tio/utils/thoughtworksparanamer

Pay attention to _readme.txt and package-info.java

thanks!

**Comment by paul-hammant** [comment]
Your top level README says "Copyright 2017 talent-tan", which should be changed to:

```
Portions copyright 2017-2018, talent-tan
Portions copyright (c) 2006-2018 Paul Hammant & ThoughtWorks Inc
Portions copyright (c) 2000-2007 INRIA, France Telecom
```

I noticed a bug in mine, and fixed it: https://github.com/paul-hammant/paranamer/commit/40a34e9c925cf52564a2fb2689dee6a2880ec95a

**Comment by tywo45** [comment]
have done, please review: https://gitee.com/tywo45/t-io/blob/master/LICENSE
