### ISSUE TITLE
Does not work for interface method.

### ISSUE THREAD

**Issue by Heartily2019** [paul-hammant/paranamer#33]
public interface HelloService {
        void hello(String name);
    }

    @Test
    public void testGetNameFromInterfaceMethod() throws NoSuchMethodException {
        Method method = HelloService.class.getDeclaredMethod("hello", String.class);
        String[] strings = new DefaultParanamer().lookupParameterNames(method);
        System.out.println(Arrays.toString(strings));
    }

**Comment by paul-hammant** [comment]
https://github.com/paul-hammant/paranamer/commit/248a13a82e3e77633623ac6b6ba0b0a0993562e6 should clarify, @Heartily2019

**Comment by Heartily2019** [comment]
Thanks for your reply. So, in the "interface method" situation, there must be extra infos such as `__PARANAMER_DATA ` field or custom parameter annotation to store the parameter's name, or we can not get the parameter's name of interface.

**Comment by paul-hammant** [comment]
Yes, that info is added for during the build for the Default (non ASM) Paranamer
