### ISSUE TITLE
Unidentified license issue

### ISSUE THREAD

**Issue by Calin-Grebles** [paul-hammant/paranamer#36]
The following license reference: "Copyright 2004 Sun Microsystems, Inc. All rights reserved. Use is subject to <a href="../../../relnotes/license.html">license terms</a>." 
is found in the following files: 
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.8/paranamer/src/resources/javadocs/jdk1.4/docs/java/io/File.html
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.8/paranamer/src/resources/javadocs/jdk6/docs/api/java/io/File.html

Where can I find the license text?

Thank you.

**Comment by paul-hammant** [comment]
JavaDoc executions using Sun/Oracle provided `javadoc` tool , and publications of generated artifacts online have **never previously been problematic for the Java community** in terms if license.  If you're representing Oracle's legal department, then will me deleting these resources from HEAD revision of the master branch be sufficient?

**Comment by Calin-Grebles** [comment]
Dear Paul,
Thank you for the quick reply.

I am an Open Source Compliance Analyst, but I'm not representing Oracle's legal department.

Here is the complete list of files (3) with this reference in paranamer-parent-2.8:
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.8/paranamer/src/resources/javadocs/jdk5/docs/java/io/File.html
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.8/paranamer/src/resources/javadocs/jdk1.4/docs/java/io/File.html
https://github.com/paul-hammant/paranamer/blob/paranamer-parent-2.8/paranamer/src/resources/javadocs/jdk6/docs/api/java/io/File.html

A functional link with the license text would be best for this case.
If these licence references do not apply, you can delete them in the master, but I would also appreciate a reply with the acknowledgement that these license references do not apply on paranamer-parent-2.8.

Kind regards,
Calin Grebles,
Open Source Compliance Analyst.

**Comment by paul-hammant** [comment]
Commit 00fb3349e47cb411fb61d8fe926f6e774ebef120 removes the items

They files formerly in `paranamer/src/resources/javadocs/` were never part of the functioning software. No prior version of Paranamer needed them to be able to function. No future version of Paranamer needs them to be able to function. End-users did not receive or use Paranamer based software that utilized them or contained them in any way. 

For example, https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar is the classic binary that end users would pull into their solution(s). Inside that file, these are the contents:

```
$ unzip paranamer-2.8.jar 

Archive:  paranamer-2.8.jar
  inflating: META-INF/MANIFEST.MF    
   creating: META-INF/maven/
   creating: META-INF/maven/com.thoughtworks.paranamer/
   creating: META-INF/maven/com.thoughtworks.paranamer/paranamer/
  inflating: META-INF/maven/com.thoughtworks.paranamer/paranamer/pom.properties  
  inflating: META-INF/maven/com.thoughtworks.paranamer/paranamer/pom.xml  
   creating: com/
   creating: com/thoughtworks/
   creating: com/thoughtworks/paranamer/
  inflating: com/thoughtworks/paranamer/AdaptiveParanamer.class  
  inflating: com/thoughtworks/paranamer/AnnotationParanamer$Jsr330Helper.class  
  inflating: com/thoughtworks/paranamer/AnnotationParanamer.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer$1.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer$ClassReader.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer$MethodCollector.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer$Type.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer$TypeCollector.class  
  inflating: com/thoughtworks/paranamer/BytecodeReadingParanamer.class  
  inflating: com/thoughtworks/paranamer/CachingParanamer$WithoutWeakReferences.class  
  inflating: com/thoughtworks/paranamer/CachingParanamer.class  
  inflating: com/thoughtworks/paranamer/DefaultParanamer.class  
  inflating: com/thoughtworks/paranamer/JavadocParanamer$DirJavadocProvider.class  
  inflating: com/thoughtworks/paranamer/JavadocParanamer$JavadocProvider.class  
  inflating: com/thoughtworks/paranamer/JavadocParanamer$UrlJavadocProvider.class  
  inflating: com/thoughtworks/paranamer/JavadocParanamer$ZipJavadocProvider.class  
  inflating: com/thoughtworks/paranamer/JavadocParanamer.class  
  inflating: com/thoughtworks/paranamer/NullParanamer.class  
  inflating: com/thoughtworks/paranamer/ParameterNamesNotFoundException.class  
  inflating: com/thoughtworks/paranamer/Paranamer.class  
  inflating: com/thoughtworks/paranamer/PositionalParanamer.class  
```

Versions other than 2.8 would be the same.  The deleting action I just performed would be similarly actionable for 2.7 and versions prior, and not impede the ability of the "jar" to be made for distribution to end users.

Does this address your concerns?

**Comment by Calin-Grebles** [comment]
Yes, thank you for your help in making light on this subject.
